# This file was generated by GoReleaser. DO NOT EDIT.
cask "ext" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0aef7a80430a76304b31bd95b28ab887d3998f7cde93683cf70863abf51dff3b"
      url "https://github.com/tjq/extendo-cli/releases/download/v#{version}/ext_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b3286c363e72d0e80385e42493f3f5f4dc10cd4fccf4148e6f7f92fec8a0de2"
      url "https://github.com/tjq/extendo-cli/releases/download/v#{version}/ext_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ext"
  desc "Terminal picker for the clipboard history the extendo macOS app keeps"
  homepage "https://github.com/tjq/extendo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ext"
  bash_completion "completions/ext.bash"
  fish_completion "completions/ext.fish"
  zsh_completion "completions/_ext"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ext"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ext is on your PATH already. To bind ctrl-G to the picker, run:

      ext install

    Then open a new terminal, or source the profile it names.
  EOS
end
