# This file was generated by GoReleaser. DO NOT EDIT.
cask "ext" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a5ab99438a6d2ff64f467c7b57273c272bc5da001f9f185b145804eb2dcfb1c4"
      url "https://github.com/tjq/extendo-cli/releases/download/v#{version}/ext_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c4f8299cfdc027bc0b198e86e7b548d9bf91db3a087062480e52613fbd86e554"
      url "https://github.com/tjq/extendo-cli/releases/download/v#{version}/ext_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ext"
  desc "Terminal picker for the clipboard history the extendo macOS app keeps"
  homepage "https://github.com/tjq/extendo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ext"
  bash_completion "completions/ext.bash"
  fish_completion "completions/ext.fish"
  zsh_completion "completions/_ext"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ext"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ext is on your PATH already. To bind ctrl-G to the picker, run:

      ext install

    Then open a new terminal, or source the profile it names.
  EOS
end
