# This file was generated by GoReleaser. DO NOT EDIT.
cask "ext" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e4988030e03d9d1c6bd2185b01f6de62a3d87b9464db5adc5fd10a3b898fa976"
      url "https://github.com/tjq/extendo-cli/releases/download/v#{version}/ext_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9dd1fa6f99530aa0f2015fa93bb2caa10eb7fc4332a0d5ad7a7f3d5e639c4176"
      url "https://github.com/tjq/extendo-cli/releases/download/v#{version}/ext_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ext"
  desc "Terminal picker for the clipboard history the extendo macOS app keeps"
  homepage "https://github.com/tjq/extendo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ext"
  bash_completion "completions/ext.bash"
  fish_completion "completions/ext.fish"
  zsh_completion "completions/_ext"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ext"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ext is on your PATH already. To bind ctrl-G to the picker, run:

      ext install

    Then open a new terminal, or source the profile it names.

    A shell binding only fires at the shell's own prompt. To reach the
    picker while a program owns the terminal — a password prompt, an
    editor, a REPL — bind it in tmux instead:

      ext install --tmux
  EOS
end
